# Generated by Django 3.1.3 on 2021-06-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210611_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_pic',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
