# Generated by Django 3.1.3 on 2021-06-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210611_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_title',
            field=models.CharField(max_length=200),
        ),
    ]
