# Generated by Django 3.1.3 on 2021-06-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210611_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_pic',
            new_name='image',
        ),
    ]
