# Generated by Django 3.1.3 on 2021-06-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Table',
        ),
    ]
