# Generated by Django 3.1.3 on 2021-06-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
