# Generated by Django 3.1.3 on 2021-06-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210612_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
